# Generated by Django 4.2.17 on 2024-12-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='health_record',
        ),
    ]
