# Generated by Django 4.2.17 on 2024-12-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animaltype',
            old_name='desciription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
