# Generated by Django 4.2.17 on 2024-12-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_animal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('pending', 'Onay Bekliyor'), ('active', 'Aktif')], default='pending', max_length=10),
        ),
    ]
